config/routes.rb
Utilus::Application.routes.draw do
  resources :flags

  root :to => 'pages#home'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'

  resources :votes
 
  resources :questions

  resources :answers

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question
  

  has_many :votes, :dependent => :destroy
  has_many :flags, :dependent => :destroy

  validates :text, :presence => true,
                  :length => {:within => 1..130}
  validates_exclusion_of :text, :in => %w(answer), :message => "Write something"

  default_scope :order => 'updated_at DESC'


  cattr_reader :per_page
  @@per_page = 10


end

app/models/flag.rb
class Flag < ActiveRecord::Base

belongs_to :answer
default_scope :order => 'updated_at DESC'

end

app/models/question.rb
class Question < ActiveRecord::Base

has_many :answers, :dependent => :destroy

validates :title, :presence => true,
                  :length => {:within => 1..130}
  
default_scope :order => 'updated_at DESC'

cattr_reader :per_page
  @@per_page = 10


end

app/models/vote.rb
class Vote < ActiveRecord::Base

belongs_to :answer

default_scope :order => 'updated_at DESC'



end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.xml
  def index
    @answers = Answer.paginate(:page => params[:page])


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.xml
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.xml
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.xml
  def create
    @answer = Answer.new(params[:answer])
      if @answer.save
        redirect_to( root_path, :notice => "Answer #{Answer.count} created. Here´s another question.")
      else
        redirect_to root_path
      end
  end

  # PUT /answers/1
  # PUT /answers/1.xml
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to(@answer, :notice => 'Answer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @answer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.xml
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to root_path, :notice => "Answer deleted. Hopefully that´s what we want." }
      format.xml  { head :ok }
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController
  # GET /flags
  # GET /flags.xml
  def index
    @flags = Flag.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @flags }
    end
  end


  # POST /flags
  # POST /flags.xml
  def create
    @flag = Flag.new(:answer_id => params[:answer_id])
    message="Thanks for flagging that question! Here´s another question."
      if @flag.save
        redirect_to root_path, :notice => message
      else
        format.html { render :action => "new" }
      end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    offset=rand(Question.count)
    @question=Question.first(:offset => offset)
    @feed=@question.answers
    @answer=Answer.new(:question => @question)

  end

  def contact
  end

  def about
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.xml
  def index
    @questions = Question.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])
    @feed=@question.answers
    @answer=Answer.new(:question => @question)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to(@question, :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(@question, :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # GET /votes
  # GET /votes.xml
  def index
    @votes = Vote.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @votes }
    end
  end

  # GET /votes/new
  # POST /votes.xml
  def create
    @vote = Vote.new(:answer_id => params[:answer_id])
    message="Vote #{Vote.count +1} recorded, thanks. Here´s another question."
      if @vote.save
        redirect_to root_path, :notice => message
      else
        redirect_to :back, :notice => "Error, somewhere. Sorry".
      end
    end
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<%= page_entries_info @answers %><%= will_paginate %>
<table>

  <% @answers.each do |answer| %>
  <tr>
    <td><strong><%= link_to answer.question.title, answer.question%></strong>
    </br>
    <%=answer.text %> </br><%= "[#{pluralize(v=answer.votes.count,"votes")} and #{pluralize(f=answer.flags.count,"flags")}. Added #{time_ago_in_words(answer.created_at)} ago.]" %> </td>

  <td> <%= link_to 'x', answer, :confirm => 'Answer has more flags than votes. Delete?', :method => :delete if f>v%></td>
    </tr>
<% end %>
</table>

<%= will_paginate %>
<br />

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @answer.text %>
</p>

<p>
  <b>Question:</b>
  <%= @answer.question_id %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/flags/_form.html.erb
<%= form_for(@flag) do |f| %>
  <% if @flag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flag.errors.count, "error") %> prohibited this flag from being saved:</h2>

      <ul>
      <% @flag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answer_id %><br />
    <%= f.text_field :answer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flags/edit.html.erb
<h1>Editing flag</h1>

<%= render 'form' %>

<%= link_to 'Show', @flag %> |
<%= link_to 'Back', flags_path %>

app/views/flags/index.html.erb
<h1>Listing offensive answers</h1>

<%= page_entries_info @flags %><%= will_paginate %>

<table>

<% @flags.each do |flag| %>
  <tr>
    <td>
    Flaged <%= time_ago_in_words(flag.created_at) %>  ago.</br>
    </td>
    <td>
      <strong>Question:</strong> <%=link_to flag.answer.question.title, flag.answer.question %> (<%= pluralize(flag.answer.question.answers.count,"answer")%> total) </br>
      <strong>Answer:</strong> <%= flag.answer.text%> ( <%= pluralize(flag.answer.votes.count,"vote")%>/ <%= pluralize(flag.answer.flags.count,"flag")%> )</br>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/flags/new.html.erb
<h1>New flag</h1>

<%= render 'form' %>

<%= link_to 'Back', flags_path %>

app/views/flags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Answer:</b>
  <%= @flag.answer_id %>
</p>


<%= link_to 'Edit', edit_flag_path(@flag) %> |
<%= link_to 'Back', flags_path %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
  </ul>
  </nav>
</footer>



<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-328064-16']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Add your question", new_question_path %></li>
   </ul>
  </nav>
  </header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]--> 
  
<%= javascript_include_tag :defaults %>
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>

  <title> <%= "Util us" %></title>
</head>
<body>
<div class="container">
  <%= render 'layouts/header' %>

  <section class="round">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </section>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>

</div>

</body>
</html>

app/views/pages/about.html.erb
<h3>Here is what you can do</h3>

<p>

<ul>

  <li>We´ve got <%= link_to pluralize(Question.count, "question"), questions_path %>.
  <li>Add a <%= link_to "question", new_question_path %>.
  <li>Go <%= link_to "answer", root_path %> some random question.
  <li>We´ve got <%= link_to pluralize(Answer.count, "answer") , answers_path %>.
  <li>We´ve got <%= link_to pluralize(Vote.count, "vote") , votes_path %> to answers.
  <li>We´ve got <%= link_to pluralize(Flag.count, "report") , flags_path %> of potentially offensive answers.

</ul>

app/views/pages/contact.html.erb
<h3>Release early, release often</h3>


This little experiment is on very early stages, but If you need to contact me you can find me <%= link_to "here", "http://brunosan.eu/contact" %>

app/views/pages/home.html.erb
Ask <strong>short</strong> <%= link_to "questions", questions_path %>.
Get <strong>short</strong> <%= link_to "answers", answers_path %>.
<p>
<br/>
<%= link_to "Skip question", root_path %>
<h2><%= @question.title %></h2>
<br/>
<a href="http://twitter.com/share" class="twitter-share-button" data-url="<%= question_url(@question) %>" data-count="horizontal" data-via="brunosan">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<br/>
<% unless @feed.empty? %>
Vote the answer you like most:  
<table class="question" summary="Randmom question">
  <tr>
    <%= render "shared/feed"  %>
  </tr>
  </table>
  ... or have your saying.
<%else %>
  This question has no anwsers no far.
  Why don´t you add one?
<%end %>
<table class="question">
    <tr>
      <%= render "shared/answer_form" %>
  </tr>
</table>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, :width=> 30 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<%= page_entries_info @questions %> <%= will_paginate %>
<table>
  <tr>
    <th>Title</th>
    <th>Answers</th>
    <th>Sent</th>
    <th></th>
  </tr>

  <% @questions.each do |question| %>

  <tr>
    <td><%= link_to truncate(question.title,:lenth =>75,:separator =>'...'), question %></td>
    <td><%= a=question.answers.count %></td>
    <td><%= time_ago_in_words(question.updated_at) %> ago</td>
    <td><%= link_to 'x', question, :confirm => 'Deleting question without answer. Are you sure?', :method => :delete if a == 0%></td>
  </tr>
<% end %>
</table>
<%= will_paginate %>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h4>Make short Questions</h4>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
<h3><%= @question.title %></h3>
</p>

<br/>
<a href="http://twitter.com/share" class="twitter-share-button" data-url="<%= question_url(@question) %>" data-count="horizontal" data-via="brunosan">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<br/>

<p>
  Asked <%= time_ago_in_words(@question.updated_at) %> ago.
</p>
  <% unless @feed.empty? %>
    <%=pluralize(@feed.count, "answer") %> so far:
    <table>
      <th></th>
      <th>Votes</th>
      <th>Flags</th>
      <%= render "shared/feed"  %>
    </table>
  <%else %>
    Hold tight, this question has no anwsers <strong>yet</strong>.
  <%end %>
  ...or add your answer
  <table class="question">
    <tr>
      <%= render "shared/answer_form" %>
  </tr>
</table>

app/views/shared/_answer_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <tr>
    <td>
      <%= f.text_field :text %>
    </td>
    <td>
    <%= f.hidden_field :question_id, :value=>@question.id %>
    <%= f.submit %>
    </td>
  </tr>

<% end %>

app/views/shared/_feed.html.erb
<% @feed.each do |answer| %> 
<tr>
  <td class="anwser">
      <%= answer.text %>
    </td>
    <% v=answer.votes.count %>
    <% f=answer.flags.count %>
    <td><%=pluralize(v,"votes")%> <%= button_to "Add 1 vote", {:controller => "votes", :action => "create", :answer_id => answer.id}%></td>
    <td><%=pluralize(f,"flags")%>
      <% if f-1 < v  %>
        <%= button_to "Flag", {:controller => "flags", :action => "create", :answer_id => answer.id} ,
            :confirm => "You are reporting this as offensive. Sure?"%></td>
        <%else %>
          </br><%= link_to "Delete?", answer, :method => :delete, :confirm => "This answer has more flags than votes. Delete answer?"%></td>
        <% end %>

</tr>

<% end %>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% a=Answer.find(params[:answer_id]) %>
  <%= a.question.title %> </br>
  <%= a.text %> </br>

  <div class="field">
    <%= f.text_field :answer_id, :value => params[:answer_id] %>
    <%= f.text_field :value, :value => 1 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<%= page_entries_info @votes %><%= will_paginate %>

<table>

<% @votes.each do |vote| %>
  <tr>
    <td>
    Voted <%= time_ago_in_words(vote.created_at) %>  ago.</br>
    </td>
    <td>
      <strong>Question:</strong> <%=link_to vote.answer.question.title, vote.answer.question %> (<%= pluralize(vote.answer.question.answers.count,"answer")%> total) </br>
      <strong>Answer:</strong> <%= vote.answer.text%> ( <%= pluralize(vote.answer.votes.count,"vote")%>/ <%= pluralize(vote.answer.flags.count,"flag")%> )</br>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Answer:</b>
  <%= @vote.answer_id %>
</p>

<p>
  <b>Value:</b>
  <%= @vote.value %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>